# This is a basic workflow to help you get started with Actions

name: Merger_To_Public

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@public
    - name: checkout_publice
      run: 
        git pull orign public,
        git merge develop，
        git push origin public.
         
    - name: Run a multi-line script
      run: echo "Update public."
